### ISSUE TITLE
Ex 1 Challenge 3 - Is this correct?

### ISSUE THREAD

**Issue by cybergoof** [bluemountaincyber/building-detections-aws#2]
Is this the real name for the honey file?  Maybe a note saying its not a typo

![image](https://user-images.githubusercontent.com/3196612/227959503-2225c3d2-ace8-4af4-8697-ce23633f9bbb.png)

**Comment by ryananicholson** [comment]
Fixed. File is named `password-backup.txt`. Give it a couple minutes for CloudFront to lose its cache of that page.
