### ISSUE TITLE
Ex 2 - Challenge 3

### ISSUE THREAD

**Issue by cybergoof** [bluemountaincyber/building-detections-aws#3]
When I go to CloudTrail page, I get this:

![image](https://user-images.githubusercontent.com/3196612/227964686-40bc6cb6-e461-4835-9a49-7cdeb2c2fdcf.png)

I would consider telling them to open the left hand pane and selecting the Dashboard.  

Or, give them this link directly - https://us-east-1.console.aws.amazon.com/cloudtrail/home?region=us-east-1#/dashboard

**Comment by ryananicholson** [comment]
The lab has you go here: https://us-east-1.console.aws.amazon.com/cloudtrail/home?region=us-east-1#/trails when clicking the link. Does it not take you to the trails section?

**Comment by cybergoof** [comment]
It takes me to the trails page, but not the "Dashboard" for me.  I get the link above, and have to open the left hand pane and select "dashboard".

Updating the link would take you to the dashboard, I think.  Which is where your screenshots start.

**Comment by ryananicholson** [comment]
I'm still not seeing it

<img width="653" alt="image" src="https://user-images.githubusercontent.com/13158109/228058913-a2aa03aa-53a5-44e8-bf8c-226d6491e59d.png">


The link is https://us-east-1.console.aws.amazon.com/cloudtrail/home?region=us-east-1#/trails

**Comment by cybergoof** [comment]
I'm not seeing it either anymore.  It might have been a fluke of some kind.  No worries
